server:
  port: 8080

spring:
  application:
    name: ${WMS_NAME}
  banner:
    location: classpath:/banner/wmsbanner
  datasource:
    url: jdbc:mariadb://${WMS_MARIADB_HOST}:${WMS_MARIADB_PORT}/${WMS_MARIADB_NAME}
    username: ${WMS_MARIADB_USERNAME}
    password: ${WMS_MARIADB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
